name: Deploy to Informatica IICS

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Informatica IICS
        run: |
          echo "Authenticating with IICS..."
          RESPONSE=$(curl -X POST "https://<IICS_URL>/v3/login" \
               -H "Content-Type: application/json" \
               -d '{"username": "${{ secrets.IICS_USERNAME }}", "password": "${{ secrets.IICS_PASSWORD }}"}')
          TOKEN=$(echo $RESPONSE | jq -r '.token')
          echo "::add-mask::$TOKEN"
          echo "INFA_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Deploy Mapping to Informatica
        run: |
          echo "Deploying XML Mapping to Informatica..."
          curl -X POST "https://<IICS_URL>/v3/mapping/import" \
               -H "Authorization: Bearer $INFA_TOKEN" \
               -F "file=@MyMapping.xml"
